name: Build and Deploy to Cloud Run job

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: stoked-genius-391609 
  # TODO: update Google Cloud project id
  GAR_LOCATION: us-central1 
  # TODO: update Artifact Registry location
  CR_JOB: cloud-run-source-deploy 
  # TODO: update Cloud Run service name
  REGION: us-central1 
  # TODO: update Cloud Run service region
  IMAGE: screenshot1
  # TODO: update Cloud Run service region

jobs:
  deploy:
    name: Deploy to Cloud Run job
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'stoked-genius-391609'
          #token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.CR_JOB }}/${{ env.IMAGE }}:${{ github.sha }}" -f Dockerfile /screenshot/

          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
          
          #gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ env.GAR_LOCATION }}-docker.pkg.dev
          
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE }}:${{ github.sha }}"
